name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK
      uses: Sxinar/buildozer-action@main
      id: buildozer
      with:
        workdir: ./
        buildozer_version: master

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
