name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3-dev \
          python3-setuptools \
          python3-wheel \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          unzip \
          zip
    
    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython
    
    - name: Initialize buildozer
      run: |
        yes | buildozer init || echo "Buildozer init completed"
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: wellness-tracker-debug-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: List generated files
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ 2>/dev/null || echo "No bin directory found"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
